language: python
python:
 - "2.6"
 - "2.7"
# Someday, soon.
# - "3.2"
install:
 - pip install --upgrade setuptools pip
 - python setup.py install
 - pip install arrow
script: python setup.py test
env: TRAVIS_CI=True
notifications:
    email: false
    irc:
        - "irc.freenode.net#fedora-apps"
    on_success: change
    on_failure: change
